# Generated by Django 4.2 on 2023-04-10 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TextPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text1", models.TextField(max_length=2048)),
                ("text2", models.TextField(max_length=2048)),
                ("is_learned_flg", models.BooleanField(default=False)),
                ("learned_ts", models.DateTimeField(blank=True, null=True)),
                ("created_ts", models.DateTimeField(auto_now_add=True)),
                ("modified_ts", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("user", "created_ts"),
            },
        ),
        migrations.CreateModel(
            name="StudyState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_passed_flg", models.BooleanField(default=False)),
                ("passed_ts", models.DateTimeField(blank=True, null=True)),
                ("created_ts", models.DateTimeField(auto_now_add=True)),
                ("modified_ts", models.DateTimeField(auto_now=True)),
                (
                    "text_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="slfrase.textpair",
                    ),
                ),
            ],
            options={
                "ordering": ("created_ts",),
            },
        ),
    ]
