# Generated by Django 4.2 on 2023-04-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slfrase", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="textpair",
            name="comment",
            field=models.TextField(blank=True, max_length=2048),
        ),
    ]
