# Generated by Django 4.2 on 2023-04-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slfrase", "0002_textpair_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="studystate",
            name="is_skipped_flg",
            field=models.BooleanField(default=False),
        ),
    ]
