# Generated by Django 4.2 on 2023-04-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slfrase", "0003_studystate_is_skipped_flg"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studystate",
            options={"ordering": ("-created_ts",)},
        ),
        migrations.AddField(
            model_name="studystate",
            name="answer",
            field=models.TextField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name="studystate",
            name="possible_answers",
            field=models.TextField(default="", max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studystate",
            name="question",
            field=models.TextField(default="", max_length=2048),
            preserve_default=False,
        ),
    ]
